package com.key.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLIP_BEAN".
*/
public class ClipBeanDao extends AbstractDao<ClipBean, Long> {

    public static final String TABLENAME = "CLIP_BEAN";

    /**
     * Properties of entity ClipBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property C_time = new Property(1, long.class, "c_time", false, "C_TIME");
        public final static Property C_text = new Property(2, String.class, "c_text", false, "C_TEXT");
    }


    public ClipBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ClipBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLIP_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"C_TIME\" INTEGER NOT NULL ," + // 1: c_time
                "\"C_TEXT\" TEXT UNIQUE );"); // 2: c_text
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLIP_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ClipBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getC_time());
 
        String c_text = entity.getC_text();
        if (c_text != null) {
            stmt.bindString(3, c_text);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ClipBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getC_time());
 
        String c_text = entity.getC_text();
        if (c_text != null) {
            stmt.bindString(3, c_text);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ClipBean readEntity(Cursor cursor, int offset) {
        ClipBean entity = new ClipBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // c_time
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // c_text
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ClipBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setC_time(cursor.getLong(offset + 1));
        entity.setC_text(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ClipBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ClipBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ClipBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
