package com.key.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.key.bean.ClipBean;

import com.key.bean.ClipBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clipBeanDaoConfig;

    private final ClipBeanDao clipBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clipBeanDaoConfig = daoConfigMap.get(ClipBeanDao.class).clone();
        clipBeanDaoConfig.initIdentityScope(type);

        clipBeanDao = new ClipBeanDao(clipBeanDaoConfig, this);

        registerDao(ClipBean.class, clipBeanDao);
    }
    
    public void clear() {
        clipBeanDaoConfig.clearIdentityScope();
    }

    public ClipBeanDao getClipBeanDao() {
        return clipBeanDao;
    }

}
